# Please add your local configuration here

# The token for accessing the telegram bot API generated by the bot father
MODE_PRODUCTION = "PRODUCTION"
MODE_DEVELOPMENT = "DEVELOPMENT"

tokens = {
    MODE_PRODUCTION: "",
    MODE_DEVELOPMENT: ""
}

DEPLOY_MODE = MODE_DEVELOPMENT
IS_DEVELOPMENT = DEPLOY_MODE == MODE_DEVELOPMENT
TELEGRAM_TOKEN = tokens[DEPLOY_MODE]
